---
title: "Chapter 7 - Ecological resemblance"
output: pdf_document
---


\begin{table}[htbp]
\caption{Distances} 
\centering
\begin{tabular}{c c c} 
\\
\hline
D & Formula & Summary \\ [0.5ex]
\hline
D1 & $\displaystyle D1(x_1, x_2) = \sqrt{\sum_{j = 1}^{p} (y_{1j} - y_{2j})^2}$ & Euclidean's distance/ pythagoras formula \\ 
D2 & $\displaystyle D2(x_1, x_2) = \sqrt{\frac{1}{p} \sum_{j = 1}^{p} (y_{1j} - y_{2j})^2}$ & Average distance of Euclidean's distance\\ 
D3 & $\displaystyle D3(x_1, x_2) = \sqrt{2 (1-\frac{\sum_{j = 1}^{p} y_{1j}*y_{2j}}{\sum_{j = 1}^{p} y_{1j}^2*\sum_{j = 1}^{p} y_{2j}^2})}$ & Chord distance \\\
D4 & $\displaystyle D4(x_1, x_2) = arc cos [1- frac{D3^2(x_1, x_2)}{2}]$ & Geodesic metric \\ 
D5 & & [0.5ex] \hline
\end{tabular}
\end{table}




##How do you choose your coefficient?##

###Asymetrical Q-mode###

*Presence/Absence descriptors or ordered classes*

1. Metric coefficients: Coefficient of community **S7** and variants **S10, S11**.
2. Semi-metric coefficients: Variantes of the coefficient of community **S8, S9, S13, S14**.
3. Non-metric coefficient **S12**.
4. Probabilistic coefficient **S27**.

*Qualitative or semiquantitative descriptors*

1. Raw abundances: 
  1.1 Non - probabilistic coefficient
    1.1.1: No Standarization by object: Same different for either abundant or rare species **S17, S18**.
    1.1.2: Standarization by object: Differences of abundant species contribute more than differences between rare species **S21, D15, D16, D17**